workflows:
  deploy:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4: {}
    - script@1:
        title: Do anything with Script step
    - deploy-to-bitrise-io@1: {}
    meta:
      bitrise.io:
        stack: osx-xcode-16.1.x
