version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Coder-boop-web/Android---test"
  dependencies_vendored = true

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "ansible"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"