name: Android

# This step triggers after the learner creates a new repository from the template.
# This workflow updates from step 0 to step 1.

# This will run every time we create push a commit to `main`.
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_start:
    name: On start
    needs: get_current_step
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      - name: Prepare a branch, and file
        run: |
          echo "Make sure we are on step 0"
          if [ "$(cat .github/steps/-step.txt)" != 0 ]; then
            echo "Current step is not 0"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=welcome-workflow
          git checkout -b $BRANCH

          echo "Create Android project structure"
          mkdir -p MyAndroidApp/app/src/main/java/com/example/myandroidapp
          mkdir -p MyAndroidApp/app/src/main/res/layout
          mkdir -p MyAndroidApp/app/src/main/res/values

          # Create empty files for Android components
          touch MyAndroidApp/app/src/main/AndroidManifest.xml
          touch MyAndroidApp/app/src/main/java/com/example/myandroidapp/MainActivity.java
          touch MyAndroidApp/app/src/main/res/layout/activity_main.xml
          touch MyAndroidApp/app/src/main/res/values/strings.xml

          echo "Make a commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add MyAndroidApp/
          git commit -m "Create basic Android project structure with empty files"

          echo "Push"
          git push --set-upstream origin $BRANCH

          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # In README.md, switch step 0 for step 1.
      - name: Update to step 1
        run: |
          # Add your command to update README or perform other actions here.
