#
name: Example workflow
on:
  push:
    branches:
      - main
jobs:
  build:
      runs-on: ububtu-latest
      steps:
      - uses: actions/checkout@v4
  
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
            token: ${{ secrets.TC_CLOUD_TOKEN }}
